/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_compiladores;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import static proyecto1_compiladores.Menu.altura;
import static proyecto1_compiladores.Menu.anchura;
import static proyecto1_compiladores.Menu.tablero;
import static proyecto1_compiladores.Menu.buscar;
/**
 *
 * @author Erick
 */
public class Ejecutable extends javax.swing.JFrame {
public static JLabel[][] objetos;
    private Object TableroFinal;
    /**
     * Creates new form Ejecutable
     */
    public Ejecutable() {
        initComponents();
        graficar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(665, 482));
        setMinimumSize(new java.awt.Dimension(665, 482));
        setResizable(false);
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejecutable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejecutable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejecutable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejecutable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejecutable().setVisible(true);
            }
        });
    }

    public void graficar(){
    int ancho_label=this.getWidth();
    int altura_label=this.getHeight();
  
    

    
    int ancho_bloque=ancho_label/anchura;
    int altura_bloque=altura_label/altura;
    
        for(int x=0;x<anchura;x++){
            for(int y=0;y<altura;y++){
              
                  objetos[x][y].setBounds(ancho_bloque*x, altura_bloque*y,ancho_bloque,altura_bloque );
                  
                       
                           this.add(objetos[x][y]);
//                           nuevo.add(this.Juego);
//                           Juego.add(jLabel1);
                          
                          
                           this.repaint();
                         
                  
                  
            }

        }
     
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
