
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Apr 06 01:08:14 CST 2015
//----------------------------------------------------

package proyecto1_compiladores;

/** CUP generated class containing symbol constants. */
public class simbolos {
  /* terminals */
  public static final int Nombre = 11;
  public static final int APersonaje = 7;
  public static final int NUMERO = 60;
  public static final int Meta = 16;
  public static final int AVillanos2 = 45;
  public static final int ACorchete = 25;
  public static final int CParentesis = 59;
  public static final int PuntoComa = 24;
  public static final int Coma = 28;
  public static final int Background = 37;
  public static final int CExtras2 = 50;
  public static final int AHeroe2 = 43;
  public static final int Enemigo = 22;
  public static final int CHeroe2 = 44;
  public static final int Alto = 39;
  public static final int AParentesis = 58;
  public static final int CElemento = 10;
  public static final int DescripcionP = 33;
  public static final int Menor = 2;
  public static final int Credito = 35;
  public static final int Heroe = 21;
  public static final int Asignacion = 27;
  public static final int AMeta2 = 55;
  public static final int Mayor = 41;
  public static final int Descripcion = 32;
  public static final int CMeta2 = 56;
  public static final int CConfiguracion = 4;
  public static final int AEscenario = 36;
  public static final int CPersonaje2 = 42;
  public static final int AElemento = 9;
  public static final int Punto = 34;
  public static final int Bonus = 18;
  public static final int ABonus2 = 53;
  public static final int CBonus2 = 54;
  public static final int AFondo = 5;
  public static final int Destruccion = 15;
  public static final int CFondo = 6;
  public static final int CPersonaje = 8;
  public static final int ID = 29;
  public static final int CVillanos2 = 46;
  public static final int APersonaje2 = 40;
  public static final int Vida = 13;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int CParedes2 = 48;
  public static final int Tipo = 14;
  public static final int Imagen = 12;
  public static final int AParedes2 = 47;
  public static final int URLW = 30;
  public static final int Bloque = 17;
  public static final int CEscenario = 57;
  public static final int Ancho = 38;
  public static final int URLL = 31;
  public static final int AConfiguracion = 3;
  public static final int Bomba = 19;
  public static final int Arma = 20;
  public static final int CCorchete = 26;
  public static final int AExtras2 = 49;
  public static final int AArmas2 = 51;
  public static final int CArmas2 = 52;
  public static final int Comillas = 23;
}

